### ISSUE TITLE
this function is not supported by this system

### ISSUE THREAD

**Issue by benzen** [karma-runner/karma-ie-launcher#10]
Running IE 10 on windows 7

I get this error when running test from jenkins
```
Error: This function is not supported on this system.
```
But i can run the same test, when connected on the same machine with admin or normal user by executing karma

**Comment by adestis-ds** [comment]
+1 (IE 11 on Windows 8.1)

**Comment by KindWizzard** [comment]
+1 (IE 11 on Windows 8.1)

**Comment by KindWizzard** [comment]
It seems like that the problem is with this IE bug:
https://connect.microsoft.com/IE/feedback/details/794531/getting-an-exception-this-function-is-not-supported-on-this-system-when-using-localstorage-when-ie-started-under-the-windows-service

**Comment by Dignifiedquire** [comment]
If that is that bug, there is nothing we can do from this side I'm afraid
