### ISSUE TITLE
Multiple instances of IE instead of 1

### ISSUE THREAD

**Issue by hanct** [karma-runner/karma-ie-launcher#100]
Hi,
I am new to this karma-ie-launcher.  I manage to configure karma.config.js, such that when i start the karma (in watch mode), it automatically starts  IE. but the problem is, it starts 3 instances of IE, so I was wondering how to control the number of IE instance to launch? What is the advantage of launching more than one instances?

**Comment by hanct** [comment]
Manage to resolve this issue with the solution proposed here. 
[https://github.com/karma-runner/karma-ie-launcher#running-ie-in-no-add-ons-mode](url)

**Comment by reduckted** [comment]
Correct link: https://github.com/karma-runner/karma-ie-launcher#running-ie-in-no-add-ons-mode
