### ISSUE TITLE
IE Karma - Travis - SauceLabs 

### ISSUE THREAD

**Issue by SergioCrisostomo** [karma-runner/karma-ie-launcher#11]
I am having problems with IE when testing with Karma on Travis/SauceLabs

On IE6 it connects to SauceLabs, and I can see "Karma-Starting" on the screen. But nothings happens and I get a timeout in the end.
`No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.`
Any ideas on what to try?

Thanks!

**Comment by Dignifiedquire** [comment]
Are you using the `karma-sauce-launcher` or the `karma-ie-launcher?

**Comment by SergioCrisostomo** [comment]
@Dignifiedquire the `karma-ie-launcher`, but actually since this post was created I dropped support for IE6 & 7 so I'm not testing it anymore. If you feel for closing this issue sound fine by me.
Cheers

**Comment by Dignifiedquire** [comment]
Okay thanks for the quick response. Enjoy karma and IE testing ;)

**Comment by JamesMGreene** [comment]
I still see this issue with IE6 on SauceLabs using the `karma-sauce-launcher`.  :confused:
