### ISSUE TITLE
Internet Explorer process failed to be killed after test run

### ISSUE THREAD

**Issue by Dacke** [karma-runner/karma-ie-launcher#12]
I believe that this is functionality that is broken as a result of the update the Karma 0.12.  I believe this because this used to work find in the previous version of Karma, but now fails to stop the iexplorer process upon completion of the tests.

I've set the captureTimeout to 5000[ms] and singleRun to true and it still will not exit the process.  
{
    browsers: ['PhantomJS', 'IE'],
    captureTimeout: 5000,
    singleRun: true
}
If I open another window and type "pskill iexplore" (using sysinternals tool) then karma exits normally and without error.

This is killing my continuous integration server (TeamCity) because it appears that the build has hung up and I have to stop it.

karma@0.12.0
karma-cli@0.0.4
karma-jasmine@0.1.5
karma-ie-launcher@0.1.2
karma-phantomjs-launcher@0.1.2

![karma-ie-version](https://f.cloud.github.com/assets/1412995/2397612/b877e83e-a9ec-11e3-8ca6-a531dbe49cb8.jpg)

**Comment by moattarwork** [comment]
I have the same issue with IE9
