### ISSUE TITLE
README.md not present in NPM package causing warning.

### ISSUE THREAD

**Issue by rogierschouten** [karma-runner/karma-ie-launcher#28]
Just a minor thing: the NPM package does not include a README. This causes the npm install command to display a warning each time. Small error small fix...?

$ npm install
npm WARN package.json karma-ie-launcher@0.1.5 No README data
npm WARN package.json karma-chrome-launcher@0.1.4 No README data

**Comment by urasquirrel** [comment]
+1

**Comment by JaKXz** [comment]
+1

**Comment by Dignifiedquire** [comment]
Fixed in `0.2.0`
