### ISSUE TITLE
IE process does not terminate when karma is terminated

### ISSUE THREAD

**Issue by nehz** [karma-runner/karma-ie-launcher#32]
Two processes are spawned, one is terminated when karma terminates, however the the other remaining process stays running.

This might be related to #12 ?

karma@0.12.31
karma-ie-launcher@0.1.5

**Comment by Dignifiedquire** [comment]
Might be, do you have a small repro for me to try out?

**Comment by nehz** [comment]
Can't reproduce this any more, seems to be fixed
